input("before the game start we want to make sure that you know that 1=yes and 2=no")
nombre = input("What is going to be the name of your caracter? ")
input("")
print("This is the history of the chaneque named", nombre)
input("")
history = int(
    input("select the game: Juego Fregón: Origins or Juego Fregón: Respiration of the Wild. "
    ))
print("")
if (history == 1):
    print("The chaneque", nombre, " wakes up thirsty")
    input("")
    print(nombre, "needs to drink chocomilk")
    input("")
    print("But he is scared to go downstairs")
    input("")
    DoctorSexo = int(input("Do you want to go downstairs? "))
    if(DoctorSexo == 1):
      print(nombre, "goes down the stairs ")
      input("")
      print("then he checks if thre is some chocomolk dust left")
      input("")
      print("realazing there is no chcomolk left")
      input("")
      print(nombre, "starts a ritual to invoke the devil")
      input("")
      print("the devil asks a question to you")
      input("")
      print("tell me", nombre, "why did you waked me up?")
      print("i want some chocomilk")
      input("")
      print("alright, if thats what you want")
      input("")
      print("that is what you will recieve")
      input("")
      print("The devil takes you to the underworld to do a task for him")
      input("")
      print("I want you to kill the chanekoide that is in front of you")
      input("")
      print("All right")
      input("")
      print("*You killed the chanekoide*")
      input("")
      print("The Devil says")
      input("")
      print("Now that you killed the chanekoide i will lead you to the chocomilk")
      input("")
      print("you take the chanekoide XP ")
      input("")
      print(nombre," make a shield")
      input("")
      print("then the ", nombre, "use the xp to make a shield with durability 3")
      input("")
      print(nombre, " skinning the chanekoide")
      input("")
      print(nombre," makes an armadura with the skin of the chanekoide")
      input("")
      print(nombre," go to the hell")
      input("")
      print(nombre," get lost on the hell and trie to escape")
      input("")
      input("then you fall on lava")
      input("")
      print(nombre, " trie to use water but it can't")
      input("")
      print(nombre," almost get killed by the lava")
      input("")
      print("n word")
      print(nombre, " find the devil")
      input("")
      print("amogus")
      print(nombre, " threat the devil")
      input("")
      print("trolmaster69")
      input("")
      print(nombre," retar the devil to a battle")
      input("")
      print("no quema cuh")
      print("the devil and you do a battle of...")
      input("")
      print("XD")
      input("")
      print("ROCK, PAPER OR CISORS")
      input("")
      print("the devil becomes a super racist thing")
      input("")
      print("you used rock")
      input("")
      print("the devil used scissors")
      input("")
      print("lol")
      input("")
      print("ez win lmao")
      input("")
      print("you get mad with the devil and you build a shootgun with a piece of paper")
      input("")
      print("the you shoot the devil right in his chest blowing a futbol ball sized hole")
      input("")
      print("the devil used emoticon")
      input("")
      print("you start making the emotiza insana")
      input("")
      print("the devil is crying")
      input("")
      print("you feel bad for the devil")
      input("")
      print("so you shoot him in the head")
      input("")
      print("he stopped crying")
      input("")
      print("ez solution time to get insano WASAAAAAA👻👻👻")
      input("")
      print("now you are in the WAZAAAA mode👻👻👻👻")
      input("")
      print("you find the chocomilk")
      input("")
      print("you grabbed your drink")
      input("")
      print("you dropped the chocomilk")
      input("")
      print("the you get out of insano mode because you dont have your chokomilk and your dua of frifai left you")
      input("")
      print("you opened another portal")
      input("")
      print("you find the devil 2")
      input("")
      print("with your shootgun you shoot the devil 2")
      input("")
      print("he used racisim")
      input("")
      print("he is more racist than TRUMP")
      input("")
      print("you feel bad")
      input("")
      print(",")
      input("")
      print("then you start crying")
      input("")
      print("you download twitter")
      input("")
      print("you funar the devil")
      input("")
      print("the devil is funado by the feminist in twitter")
      input("")
      print("the devil don't want to be alive")
      input("")
      print("the devil kills himself")
      input("")
      print("you revive the devil")
      input("")
      print("you make fun because bolivia don't have ocean")
      input("")
      print("you start fighting with the ejercito of bolivia")
      input("")
      print("but you realize they are aliens")
      input("")
      print("so you and the devil make a team")
      input("")
      print("to kill all of them")
      input("")
      print("the devil enters wazaaaa mode")
      input("")
      print("you go insano mode and you levantar mira on them")
      input("")
      if(DoctorSexo == 2):
        print("you decide to stay in your room")
        input("")
        print("you go back to sleep")
        input("")
        print("The End")









      
else:
  while True:
    if(history==2):
      print("The", nombre," wakes up 100 years after he goes to sleep, ")
      print("then he is thirsty of a chokomilk")
      input("")
      print("The next thing that", nombre," do, is to take an ipad")
      input("")
      print("then he found an old drunk and tasty men")
      input("")
      print("the old man tells you that you must save his daughter in exchange for a chokomilk")
      print(nombre, "tells yes I will save her")
  
    
      print(nombre, "starts punching a tree")
      input("")
      print(nombre, "collects the wood")
      input("")
      print(nombre, "makes a wood sword")
      input("")
      print(nombre, "kills the old man")
      input("")
      print(nombre, "finds a chanke")
      input("")
      print("Do you want to kill the chaneke?")
      print(nombre, "have successfully killed your only friend")
      print(nombre, "you get dressed")
      input("")
      print(nombre, "you go to talk to the old man")
      input("")
      print("the oldman test you")
      input("")
      print("the oldman says that you must win him in a rock paper scissor game")
      input("")
      print("an incredible miracle happens and the old man dies and you win")
      input("")
      print(nombre, " stole a paraguas that the old man had")
      input("")
      print("you tried to use the paraguas but you dont and the only one that could help was the old man")
      input("")
      print("you have to spend another 100 years to learn how to use the paraguas")
      input("")
      print("on the first year you find a magical snail and he says he can help you")
      input("")
      print("8 for accept the help or 7 for eat the snail")
      input(nombre, "accept the help")
      chilaquiles = input()
        if(chilaquiles==8):
          print("you accepted the help")
          input("")
          print("like a year ago a miracle happened and a strange form kills the snail")
          input("")
      
         print(nombre, "eats the snail")
            if(chilaquiles==7):
          print(nombre, "you killed the snail")
         input("")
          print(nombre, "you eat the snail even his shell")
          input("")
          print("the second year starts")
          input("")
          print(nombre, "you found a strange mushroom")
         input("")
         print("5 for eat the mushroom 1 for dont eat the mushroom")
              monke = input()
            if(monke==1):
              print(nombre, "you dont eat the strange mushroom and nothing happens")
              if(monke==5):
                print(nombre, "you eat the mushroom")
                input("")
                print("you fell asleep")
                input("")
              print("you are now in another dimension")
              input("")
                print("you find the god tenoshtotojok")
               input("")
                print("tenoshtotojok challenges you to have a pokemon battle")
                input("")
                print("you found a gun")
                input("")
                 print("you accidentally shoot him in the face")
                input("")
                print("you have oficially killed a god")
                input("")
                print("after killing the god you earn power to use the paraguas")
                input("")
                print(nombre, "wakes up and realized that he has been sleeping over 86 years")
                input("")
                print("now you can escape from the dead body of a old man that possibly wanted to molest you")
                input("")
                print("you are now in your way to the castle")
                input("")
                print("you find a curios men that offers you the direct way to go to the castle")
                input("")
                print(nombre, "doesnt understand a thing so you hit him in his partes")
                input("")
                print("he starts dying and you start to punch him")
                input("")
                print("you grab his things")
                input("")
                print("somehow you get lost")
                input("")
                print("you found a village")
                input("")
                print("3 for kill all the villagers because you are racist or 6 for no")
                print("")
                pan = input()
                if(pan==6):
                  print("see the village but dont kill them and die of hunger")
                  if(pan==3):
                    print("you kill all the villagers")
                    input("")
                    print(nombre, "sell villagers as slaves for the most rich village")
                    input("")
                    print(nombre, "got 10 Billion dolars in effective")
                    input("")
                    print("you bought all the kingdoms that could possibly exist")
                    input("")
                    print("you became the most powerfull king and you decide to be Duarte 2")
                      input("")
                      print("now all your villagers hate you and you escape from the country")
                      input("")
                      print("you remembered that you need to save the princess")
                      input("")
                      print("you have returned to your country")
                      input("")
                      print(nombre, "you are now in the country")
                      input("")
                    print("now you enter to the castle")
                    input("")
                    print("while you are exploring the castle you find a bunch of guardians")
                    input("")
                    print("those guardians want to help you")
                    input("")
                    print("after you spent 86 years on a island you though they are gods")
                    input("")
                    print("so you kill them")
                    input("")
                    print("while you are exploring the castle the old villagers have doxeado you")
                    input("")
                    print("now they are 5,679 villagers outwide the castle")
                    input("")
                    print("you start building a AK-47 with a wooden stick")
                    input("")
                    print("you have unlimited bullets")
                    input("")
                    print(nombre, "you start shooting all the people around the castle")
                    input("")
                    print("now you have killed 3,862")
                    input("")
                    print(nombre, "you killed the people left")
                    input("")
                    print("now you get out of the castle and loot them")
                    iut("")
                    print("now you have a better armadura and weapons")
                    input("")
                    print("the devil founds out about your matansa")
                    input("")
                    print("he starts thinking that you are the real devil")
                    input("")
                    print(nombre, "you start creating the most powerful sword ever")
                    input("")
                    print("you are walking again")
                    input("")
                    print("you spent 98 years trying to reach the devil")
                    input("")
                    print("when you reached the devil")
                    input("")
                    print("you realized that you have 3 different diseases")
                    input("")
                    print("and you have 10 min of life")
                    input("")
                    print("you spent 9 min thinking how handsome the devil is")
                    input("")
                    print("you find the devil")
                    input("")
                    print(nombre, "you have died")
                    input("")
                    print("jajaja")
                    input("")
                    print("what a bot")
                    input("")
                    print("the devil is buena onda and he gives you 1 min left of life")
                    input("")
                    print("you get mad with the devil because he is tacaño")
                    input("")
                    print("you tried attacking the devil with tour sword")
                    input("")
                    print("the sword destroyed")
                    input("")
                    print("XD")
                    input("")
                    print("you remebered that the sword was from the tianguis")
                    input("")
                    print("the devil got a heart attack")
                    input("")
                    print(nombre, "you aprovechar the bug and start kissing the devil")
                    input("")
                    print("the devil fell in love with you")
                    input("")
                    print("you killed the devil beacuse you are bad onda")
                    input("")
                    print("you start remembering something that the old man ones said you")
                    input("")
                    print("he said, barbicue bacon burger")
                    input("")
                    print("that gives tou an incredible power that can fight with the gods")
                    input("")
                    print("the god said what")
                    input("")
                    print("and you said so")
                    input("")
                    print("he got so mad that he start to crying")
                    input("")
                    print("he magically dies")
                    input("")
                    print("then the princess appears")
                    input("")
                    print("and she tolds you something that will shock you")
                    input("")
                    print("she tells you that there was never a chocomilk")
                    input("")
                    print("you start crying")
                    input("")
                    print("you remember that you had a AK-47 so you killed the princess")
                    input("")
                    print("you start playing uno with a dead body")
                    input("")
                    print("end")
                    print("the game end")
                    input("")
                    print("end")
                    input("")
                    print("the end of the end")
                    input("")
                    print("the end of the end of the end")
                    input("")
                    print("the end of the end of the end of the end")
                    input("")
                    print("is it the end???")
                    input("")
                    print("???")
                    input("")
                    print("it haven't end")
                    input("")
                    print("this is the end of the game")
                    input("")
                    print("")