print("Insert your name")
nombre=input()
print("Welcome", nombre)
producto1=input("insert your first product ")
producto2=input("insert your second product ")
producto3=input("insert your third product ")
producto4=input("insert your fourth product ")
producto5=input("insert ypur fifth product ")
price1=int(input("insert the price for your first product "))
price2=int(input("insert the price for your second product "))
price3=int(input("insert the price for your third product "))
price4=int(input("insert the price for your fourth product "))
price5=int(input("insert the price for your fifth product "))
print("_____________________")
print("Thanks for buying!")
print("")
price=price1+price2+price3+price4+price5
print("")
print("Your total price is ", price)
print("")
print("")
print("See you soon!")